services:
  api:
    build:
      context: ./GymTrackerMobile.API
      dockerfile: Dockerfile
    container_name: GymTrackerApi
    ports:
      - "5269:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=GymTrackerDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - dev-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: GymTrackerDbSqlServer
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - GymTrackerDbSqlServer-data:/var/opt/mssql
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Password123" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

networks:
  dev-network:
    driver: bridge

volumes:
  GymTrackerDbSqlServer-data: